# Generated by Django 4.0.6 on 2022-09-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fort',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('add', models.CharField(max_length=255)),
                ('add3d', models.CharField(max_length=255)),
                ('info', models.TextField()),
            ],
        ),
    ]
